language: node_js
node_js:
  - "0.10"

# only build the deploy branch
branches:
  only:
    - deploy

before_script:
  - node test/server.js . 8080 &
  - sleep 5

script:
  - phantomjs test/basictest.js localhost:8080