language: node_js
node_js:
  - "0.10"

# only build the deploy branch
branches:
  only:
    - deploy

before_install: 
  - npm install -g grunt-cli
  - npm install -g casperjs
  - phantomjs --version; casperjs --version

before_script:
  - grunt build
